"""Serve the report snapshot generated by the scheduled reporting workflow."""
from http.server import BaseHTTPRequestHandler
from pathlib import Path
import json

def load_snapshot():
    path = Path(__file__).resolve().parent.parent / "mobee_stats.json"
    data = json.loads(path.read_text())
    if not isinstance(data, dict) or not isinstance(data.get("total_games"), int):
        raise ValueError("Invalid statistics snapshot")
    data["data_source"] = "saved_report"
    return data

class handler(BaseHTTPRequestHandler):
    def do_GET(self):
        try:
            data, status = load_snapshot(), 200
        except (OSError, ValueError):
            data, status = {"error": "Statistics snapshot unavailable"}, 503
        self.send_response(status)
        self.send_header("Content-Type", "application/json")
        self.send_header("Access-Control-Allow-Origin", "*")
        self.send_header("Cache-Control", "public, s-maxage=60")
        self.end_headers()
        self.wfile.write(json.dumps(data).encode())

    def do_OPTIONS(self):
        self.send_response(200)
        self.send_header("Access-Control-Allow-Origin", "*")
        self.send_header("Access-Control-Allow-Methods", "GET, OPTIONS")
        self.send_header("Access-Control-Allow-Headers", "Content-Type")
        self.end_headers()
